
Drop table Comunidad if exists cascade;
Drop table Inmueble if exists cascade;
Drop table Factura if exists cascade;
Drop table LineaFactura if exists cascade;
Drop table Concepto if exists cascade;
Drop table NotaInformativa if exists cascade;
Drop table ReciboInmueble if exists cascade;
Drop table Propietario if exists cascade;


			
CREATE TABLE ReciboInmueble (
       idRecibo INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , FechaPago DATE
     , Importe FLOAT
     , PRIMARY KEY (idRecibo)
);
CREATE TABLE Concepto (
	   idConcepto INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , ClaveConcepto INTEGER 
     , Descripcion CHAR(50)
     , PRIMARY KEY (idConcepto)
);

CREATE TABLE Propietario (
	 
       nif INTEGER
     , idPropietario INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , Nombre CHAR(50)
     , Direccion CHAR(50)
     , Poblacion CHAR(50)
     , Telefono CHAR(9)
     , Observaciones CHAR(50)
     , FechaAlta CHAR(20)
     , Entidad INTEGER
     , NumeroCuenta INTEGER
     , PRIMARY KEY (idPropietario)
);

CREATE TABLE NotaInformativa (
       idNotaInformativa INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , FechaCalculo DATE
     , ImporteNota FLOAT
     , idRecibo INTEGER 
     , PRIMARY KEY (idNotaInformativa)
     , FOREIGN KEY (idRecibo)
                  REFERENCES ReciboInmueble (idRecibo) 
);

CREATE TABLE LineaFactura (
	   idLineaFactura INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)	
     , ImporteLinea FLOAT NOT NULL 
     , Observacion CHAR(50)
     , ClaveConcepto INTEGER 
     , idLinea INTEGER
     , PRIMARY KEY (idLineaFactura)
     , FOREIGN KEY (ClaveConcepto)
                  REFERENCES Concepto (idConcepto)
);
CREATE TABLE Factura (
       NumFactura INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , FechaFactura DATE
     , idNotaInformativa INTEGER 
     , ImporteLinea FLOAT
     , idLineaFactura INTEGER
     , PRIMARY KEY (NumFactura)
     ,  FOREIGN KEY (idNotaInformativa)
                  REFERENCES NotaInformativa (idNotaInformativa)
     , FOREIGN KEY (idLineaFactura)
                  REFERENCES LineaFactura (idLineaFactura) 
);

CREATE TABLE Comunidad (
	   idComunidad INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)

     , nombre CHAR(50)
     , calle CHAR(50)
     , poblacion CHAR(50)
     , MaxRecibosPendientes INTEGER
     , Estado CHAR(25)
     , idNotaInformativa INTEGER
     , NumFactura INTEGER
     , IdInmueble INTEGER
     , presidente INTEGER 
     , PRIMARY KEY (idComunidad)
     ,  FOREIGN KEY (NumFactura)
                  REFERENCES Factura (NumFactura)
     ,  FOREIGN KEY (idNotaInformativa)
                  REFERENCES NotaInformativa (idNotaInformativa)

);
CREATE TABLE Inmueble (
       IdInmueble INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)
     , Escalera CHAR(10)
     , Piso CHAR(10)
     , Puerta CHAR(10)
     , Porcentaje FLOAT
     , idPropietario INTEGER 
     , idComunidad INTEGER
     , idRecibo INTEGER 
	 , PRIMARY KEY (IdInmueble)
     , FOREIGN KEY (idPropietario)
                  REFERENCES Propietario (idPropietario)
     , FOREIGN KEY (idRecibo)
                  REFERENCES ReciboInmueble (idRecibo)
     , FOREIGN KEY (idComunidad)
                  REFERENCES Comunidad (idComunidad) ON DELETE CASCADE
);
 CREATE TRIGGER trig AFTER DELETE ON Comunidad 
    delete from inmueble where idcomunidad is null


