select * from inmueble;
select * from propietario;
select * from comunidad;
select * from carta;
select * from reciboinmueble;
select * from notainformativa;
select * from concepto;
select * from lineafactura;
select * from factura;